# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate libssh2-sys

Name:           rust-%{crate}
Version:        0.2.5
Release:        1%{?dist}
Summary:        Native bindings to the libssh2 library

# https://github.com/alexcrichton/ssh2-rs/issues/55
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/libssh2-sys
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
BuildRequires:  (crate(cmake) >= 0.1.2 with crate(cmake) < 0.2.0)
BuildRequires:  (crate(libc) >= 0.2.0 with crate(libc) < 0.3.0)
BuildRequires:  crate(libz-sys) >= 0.0.0
BuildRequires:  (crate(openssl-sys) >= 0.9.0 with crate(openssl-sys) < 0.10.0)
BuildRequires:  (crate(pkg-config) >= 0.3.0 with crate(pkg-config) < 0.4.0)
BuildRequires:  pkgconfig(libssh2)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libssh2)

%description    devel
Native bindings to the libssh2 library.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
# No bundled deps
rm -vrf libssh2/
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.5-1
- Initial package
