# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate slab

Name:           rust-%{crate}
Version:        0.3.0
Release:        1%{?dist}
Summary:        Simple slab allocator

License:        MIT
URL:            https://crates.io/crates/slab
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Simple slab allocator.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# https://github.com/carllerche/slab/issues/36
%cargo_test || :
%endif

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.0-1
- Initial package
