# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate libz-sys

Name:           rust-%{crate}
Version:        1.0.13
Release:        2%{?dist}
Summary:        Bindings to the system libz library (also known as zlib)

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/libz-sys
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * No [workspace]
Patch0:         libz-sys-1.0.13-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
# [dependencies]
BuildRequires:  (crate(libc) >= 0.2.0 with crate(libc) < 0.3.0)
# [build-dependencies]
BuildRequires:  (crate(gcc) >= 0.3.17 with crate(gcc) < 0.4.0)
BuildRequires:  (crate(pkg-config) >= 0.3.0 with crate(pkg-config) < 0.4.0)
BuildRequires:  pkgconfig(zlib)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(zlib)

%description    devel
Bindings to the system libz library (also known as zlib).

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
# No bundled deps
rm -vrf src/zlib-*/
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.13-2
- Rebuild

* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.13-1
- Initial package
