# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate void

Name:           rust-%{crate}
Version:        1.0.2
Release:        1%{?dist}
Summary:        Uninhabited void type for use in statically impossible cases

License:        MIT
URL:            https://crates.io/crates/void
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
The uninhabited void type for use in statically impossible cases.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sat Feb 18 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.2-1
- Initial package
