# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate bytes

Name:           rust-%{crate}
Version:        0.4.4
Release:        1%{?dist}
Summary:        Types and traits for working with bytes

# https://github.com/carllerche/bytes/pull/134
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/bytes
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(byteorder) >= 1.0.0 with crate(byteorder) < 2.0.0)
BuildRequires:  (crate(iovec) >= 0.1.0 with crate(iovec) < 0.2.0)
BuildRequires:  (crate(serde) >= 1.0.0 with crate(serde) < 2.0.0)
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(serde_test) >= 1.0.0 with crate(serde_test) < 2.0.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Types and traits for working with bytes.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
rm -vrf ci
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.4-1
- Initial package
