# Generated by rust2rpm
# Tests are not distributed, couldn't read "test/test.rs": No such file or directory (os error 2)
%bcond_with check
%global debug_package %{nil}

%global crate bytes

Name:           rust-%{crate}0.3
Version:        0.3.0
Release:        1%{?dist}
Summary:        Types and traits for working with bytes

License:        MIT
URL:            https://crates.io/crates/bytes
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(rand) >= 0.3.5 with crate(rand) < 0.4.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Types and traits for working with bytes.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
# Warnings do not terminate build
sed -i -e '/^#!\[deny(warnings)\]$/d' src/lib.rs
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.0-1
- Initial package
