# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate libc

Name:           rust-%{crate}
Version:        0.2.20
Release:        3%{?dist}
Summary:        Library for types and bindings to native C

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/libc
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# https://github.com/rust-lang/cargo/issues/3642
Patch0:         %{name}-remove-workspace.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
%{summary}.

%prep
%autosetup -n %{crate}-%{version} -p1
rm -vrf {.gitignore,.travis.yml,appveyor.yml,ci}
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Feb 24 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.20-3
- Strip unneeded files

* Sun Feb 12 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.20-2
- Add license files
- Fix license tag

* Sun Feb 12 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.20-1
- Initial package
