# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate quale

Name:           rust-%{crate}
Version:        1.0.0
Release:        1%{?dist}
Summary:        A Rust port of the `which` utility, locates an executable in the user’s path

# https://github.com/frewsxcv/rust-quale/issues/7
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/quale
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(libc) >= 0.2.0 with crate(libc) < 0.3.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
A Rust port of the `which` utility. Locates an executable in the user’s path.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# https://github.com/frewsxcv/rust-quale/issues/8
%cargo_test || :
%endif

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.0-1
- Initial package
