# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate num-iter

Name:           rust-%{crate}
Version:        0.1.33
Release:        2%{?dist}
Summary:        External iterators for generic mathematics

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/num-iter
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * No paths
Patch0:         num-iter-0.1.33-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(num-integer) >= 0.1.32 with crate(num-integer) < 0.2.0)
BuildRequires:  (crate(num-traits) >= 0.1.32 with crate(num-traits) < 0.2.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
External iterators for generic mathematics.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.33-2
- Port to use rust-packaging

* Thu Mar 02 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.33-1
- Initial package
