# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate env_logger

Name:           rust-%{crate}
Version:        0.4.0
Release:        1%{?dist}
Summary:        Logging implementation for `log` which is configured via an environment variable

# https://github.com/rust-lang-nursery/log/issues/102
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/env_logger
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
Patch0:         env_logger-0.4.0-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
BuildRequires:  (crate(log) >= 0.3.0 with crate(log) < 0.4.0)
BuildRequires:  (crate(regex) >= 0.2.0 with crate(regex) < 0.3.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
A logging implementation for `log` which is configured via an environment
variable.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sat Feb 25 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.0-1
- Initial package
