# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate tokio-io

Name:           rust-%{crate}
Version:        0.1.2
Release:        1%{?dist}
Summary:        Core I/O primitives for asynchronous I/O in Rust

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/tokio-io
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(bytes) >= 0.4.0 with crate(bytes) < 0.5.0)
BuildRequires:  (crate(futures) >= 0.1.11 with crate(futures) < 0.2.0)
BuildRequires:  (crate(log) >= 0.3.0 with crate(log) < 0.4.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Core I/O primitives for asynchronous I/O in Rust.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.2-1
- Initial package
