# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate num-traits

Name:           rust-%{crate}
Version:        0.1.36
Release:        1%{?dist}
Summary:        Numeric traits for generic mathematics

# https://github.com/rust-num/num/issues/266
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/num-traits
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Numeric traits for generic mathematics.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.36-1
- Initial package
