# Generated by rust2rpm
# Not all files distributed, couldn't read "examples/encode/main.rs": No such file or directory (os error 2)
%bcond_with check
%global debug_package %{nil}

%global crate data-encoding

Name:           rust-%{crate}
Version:        1.2.0
Release:        1%{?dist}
Summary:        Generic data encoding functions

License:        MIT
URL:            https://crates.io/crates/data-encoding
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(getopts) >= 0.2.14 with crate(getopts) < 0.3.0)
BuildRequires:  (crate(rustc-serialize) >= 0.3.16 with crate(rustc-serialize) < 0.4.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
This crate provides generic data encoding functions. It is meant to
guarantee mathematical properties, to conform to RFC 4648, to be
efficient, and to give choice between allocating and in-place
functions. It also provides an exhaustive example with similar
functionality to the base64 GNU program. It supports common bases
(base2, base4, base8, base16, hex, base32, base32hex, base64,
and base64url) and custom bases (defined on the command-line by their
padding and symbols in value order).

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.2.0-1
- Initial package
