# Generated by rust2rpm
# bincode is dependency for tests (in next version), but that makes circular dep
# serde_bytes -> bincode(dev) -> serde_bytes(dev)
%bcond_with check
%global debug_package %{nil}

%global crate serde_bytes

Name:           rust-%{crate}
Version:        0.10.0
Release:        1%{?dist}
Summary:        Optimized handling of `&[u8]` and `Vec<u8>` for Serde

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/serde_bytes
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(serde) >= 1.0.0 with crate(serde) < 2.0.0)
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(serde_derive) >= 1.0.0 with crate(serde_derive) < 2.0.0)
BuildRequires:  (crate(serde_test) >= 1.0.0 with crate(serde_test) < 2.0.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Optimized handling of `&[u8]` and `Vec<u8>` for Serde.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Thu Jun 15 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.10.0-1
- Initial package
