# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate rustc-demangle

Name:           rust-%{crate}
Version:        0.1.3
Release:        3%{?dist}
Summary:        Demangle Rust compiler symbol names

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/rustc-demangle
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
%{summary}.

%prep
%autosetup -n %{crate}-%{version}
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sun Feb 12 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.3-3
- Sync with rust2rpm generator

* Fri Feb 10 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.3-2
- Sync with rust2rpm generator

* Fri Feb 10 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.3-1
- Initial package
