# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate pocket-resources

Name:           rust-%{crate}
Version:        0.3.2
Release:        1%{?dist}
Summary:        Include resources in your applications

License:        MIT
URL:            https://crates.io/crates/pocket-resources
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Include resources in your applications.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Mon Jun 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.2-1
- Initial package
