# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate rustc_version

Name:           rust-%{crate}
Version:        0.1.7
Release:        2%{?dist}
Summary:        Library for querying the version of a installed rustc compiler

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/rustc_version
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * bump semver, https://github.com/Kimundi/rustc-version-rs/pull/10
Patch0:         rustc_version-0.1.7-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(semver) >= 0.6.0 with crate(semver) < 0.7.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
A library for querying the version of a installed rustc compiler.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.7-2
- Port to use rust-packaging

* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.7-1
- Initial package
