# Generated by rust2rpm
# Tests require nightly rust
%bcond_with check
%global debug_package %{nil}

%global crate fs2

Name:           rust-%{crate}
Version:        0.4.1
Release:        1%{?dist}
Summary:        Cross-platform file locks and file duplication.

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/fs2
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
Patch0:         fs2-0.4.1-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
BuildRequires:  crate(libc) >= 0.2.2
BuildConflicts: crate(libc) >= 0.3.0
%if %{with check}
BuildRequires:  crate(tempdir) >= 0.3.0
BuildConflicts: crate(tempdir) >= 0.4.0
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Cross-platform file locks and file duplication.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sat Feb 18 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.1-1
- Initial package
