# Generated by rust2rpm
# speculate is nightly
%bcond_with check
%global debug_package %{nil}

%global crate diff

Name:           rust-%{crate}
Version:        0.1.10
Release:        1%{?dist}
Summary:        LCS based slice and string diffing implementation

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/diff
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(quickcheck) >= 0.4.1 with crate(quickcheck) < 0.5.0)
BuildRequires:  (crate(speculate) >= 0.0.24 with crate(speculate) < 0.0.25)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
An LCS based slice and string diffing implementation.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sun Mar 05 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.10-1
- Update to 0.1.10

* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.9-1
- Initial package
