# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate ansi_term

Name:           rust-%{crate}
Version:        0.9.0
Release:        1%{?dist}
Summary:        Library for ANSI terminal colours and styles (bold, underline)

License:        MIT
URL:            https://crates.io/crates/ansi_term
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Library for ANSI terminal colours and styles (bold, underline).

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENCE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sat Feb 18 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.0-1
- Initial package
