# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate idna

Name:           rust-%{crate}
Version:        0.1.2
Release:        1%{?dist}
Summary:        IDNA (Internationalizing Domain Names in Applications) and Punycode

# https://github.com/servo/rust-url/issues/376
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/idna
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * Bump rustc-test to 0.2, https://github.com/servo/rust-url/commit/6d2411fe3ac3d470ac8edcf2524309daadb31115
Patch0:         idna-0.1.2-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(matches) >= 0.1.0 with crate(matches) < 0.2.0)
BuildRequires:  (crate(unicode-bidi) >= 0.3.0 with crate(unicode-bidi) < 0.4.0)
BuildRequires:  (crate(unicode-normalization) >= 0.1.3 with crate(unicode-normalization) < 0.2.0)
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(rustc-serialize) >= 0.3.0 with crate(rustc-serialize) < 0.4.0)
BuildRequires:  (crate(rustc-test) >= 0.2.0 with crate(rustc-test) < 0.3.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
IDNA (Internationalizing Domain Names in Applications) and Punycode.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Wed Jul 05 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.2-1
- Initial package
