# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate handlebars

Name:           rust-%{crate}
Version:        0.27.0
Release:        1%{?dist}
Summary:        Handlebars templating implemented in Rust

License:        MIT
URL:            https://crates.io/crates/handlebars
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(lazy_static) >= 0.2.2 with crate(lazy_static) < 0.3.0)
BuildRequires:  (crate(log) >= 0.3.1 with crate(log) < 0.4.0)
BuildRequires:  (crate(pest) >= 0.3.0 with crate(pest) < 0.4.0)
BuildRequires:  (crate(quick-error) >= 1.0.0 with crate(quick-error) < 2.0.0)
BuildRequires:  (crate(regex) >= 0.2.0 with crate(regex) < 0.3.0)
BuildRequires:  (crate(serde) >= 1.0.0 with crate(serde) < 2.0.0)
BuildRequires:  (crate(serde_json) >= 1.0.0 with crate(serde_json) < 2.0.0)
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(env_logger) >= 0.4.0 with crate(env_logger) < 0.5.0)
BuildRequires:  (crate(maplit) >= 0.1.3 with crate(maplit) < 0.2.0)
BuildRequires:  (crate(serde_derive) >= 1.0.0 with crate(serde_derive) < 2.0.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Handlebars templating implemented in Rust.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Thu Jul 06 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.27.0-1
- Initial package
