# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate unicode-bidi

Name:           rust-%{crate}
Version:        0.3.3
Release:        1%{?dist}
Summary:        Implementation of the Unicode Bidirectional Algorithm

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/unicode-bidi
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(matches) >= 0.1.0 with crate(matches) < 0.2.0)
BuildRequires:  (crate(serde) >= 0.8.0 with crate(serde) < 2.0.0)
BuildRequires:  (crate(serde_derive) >= 0.8.0 with crate(serde_derive) < 2.0.0)
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(serde_test) >= 0.8.0 with crate(serde_test) < 2.0.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Implementation of the Unicode Bidirectional Algorithm.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# Full tests miss files, https://github.com/servo/unicode-bidi/issues/43
%cargo_test --doc
%endif

%files          devel
%license COPYRIGHT LICENSE-MIT LICENSE-APACHE
%doc README.md AUTHORS
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Wed Jul 05 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.3-1
- Initial package
