# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate extprim_literals_macros

Name:           rust-%{crate}
Version:        2.0.0
Release:        1%{?dist}
Summary:        Internal crate to support `extprim_literals`

# https://github.com/kennytm/extprim/issues/7
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/extprim_literals_macros
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * No paths
Patch0:         extprim_literals_macros-2.0.0-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(extprim) >= 1.2.0 with crate(extprim) < 2.0.0)
BuildRequires:  (crate(procedural-masquerade) >= 0.1.1 with crate(procedural-masquerade) < 0.2.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Internal crate to support `extprim_literals`. You typically don't need this
crate directly.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Thu Jun 15 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.0.0-1
- Initial package
