# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate flame

Name:           rust-%{crate}
Version:        0.1.12
Release:        1%{?dist}
Summary:        Profiling / flamegraph library

# https://github.com/TyOverby/flame/issues/24
License:        (MIT or ASL 2.0) and BSD
URL:            https://crates.io/crates/flame
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(lazy_static) >= 0.2.0 with crate(lazy_static) < 0.3.0)
BuildRequires:  (crate(serde) >= 1.0.0 with crate(serde) < 2.0.0)
BuildRequires:  (crate(serde_derive) >= 1.0.0 with crate(serde_derive) < 2.0.0)
BuildRequires:  (crate(serde_json) >= 1.0.0 with crate(serde_json) < 2.0.0)
BuildRequires:  (crate(thread-id) >= 3.0.0 with crate(thread-id) < 4.0.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch
# Hard to find which version it is
Provides:       bundled(js-d3js)

%description    devel
A profiling / flamegraph library.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# threads test is failing, https://github.com/TyOverby/flame/issues/25
%cargo_test || :
%endif

%files          devel
%doc readme.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sat Jul 08 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.12-1
- Initial package
