# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate sha1

Name:           rust-%{crate}
Version:        0.2.0
Release:        2%{?dist}
Summary:        Minimal implementation of SHA1 for Rust

License:        BSD
URL:            https://crates.io/crates/sha1
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Newer OpenSSL
Patch0:         0001-bump-openssl-to-0.9.patch

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(openssl) >= 0.9.0 with crate(openssl) < 0.10.0)
BuildRequires:  (crate(rand) >= 0.3.0 with crate(rand) < 0.4.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Minimal implementation of SHA1 for Rust.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-2
- Port to use rust-packaging

* Mon Apr 03 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-1
- Initial package
