# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate chrono

Name:           rust-%{crate}
Version:        0.3.1
Release:        1%{?dist}
Summary:        Date and time library for Rust

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/chrono
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * Bump bincode to 0.8, https://github.com/chronotope/chrono/commit/a91981af026052d6a1b9591f3c7f18a46842a5c5
# * Remove serde feature from bincode, https://github.com/chronotope/chrono/pull/160
Patch0:         chrono-0.3.1-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(num) >= 0.1.0 with crate(num) < 0.2.0)
BuildRequires:  (crate(rustc-serialize) >= 0.3.0 with crate(rustc-serialize) < 0.4.0)
BuildRequires:  (crate(serde) >= 1.0.0 with crate(serde) < 2.0.0)
BuildRequires:  (crate(time) >= 0.1.36 with crate(time) < 0.2.0)
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(bincode) >= 0.8.0 with crate(bincode) < 0.9.0)
BuildRequires:  (crate(serde_json) >= 1.0.0 with crate(serde_json) < 2.0.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Date and time library for Rust.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE.txt
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.1-1
- Initial package
