# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate cryptovec

Name:           rust-%{crate}
Version:        0.3.4
Release:        1%{?dist}
Summary:        Vector which zeroes its memory on clears and reallocations

# license is in upstream repo, but excluded from crates.io
# ignatenkobrain: can't file issue in upstream, says Forbidden
License:        ASL 2.0
URL:            https://crates.io/crates/cryptovec
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * No windows
Patch0:         cryptovec-0.3.4-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(libc) >= 0.2.0 with crate(libc) < 0.3.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
A vector which zeroes its memory on clears and reallocations.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Tue Jun 20 2017 Martin Sehnoutka <msehnout@redhat.com> - 0.3.4-1
- Initial package
