# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate backtrace-sys

Name:           rust-%{crate}
Version:        0.1.11
Release:        1%{?dist}
Summary:        Bindings to the libbacktrace gcc library

# src/libbacktrace is BSD
License:        (MIT or ASL 2.0) and BSD
URL:            https://crates.io/crates/backtrace-sys
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(libc) >= 0.2.0 with crate(libc) < 0.3.0)
# [build-dependencies]
BuildRequires:  (crate(gcc) >= 0.3.0 with crate(gcc) < 0.4.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
# Some snapshot from 2016-11-15
Provides:       bundled(libbacktrace)
BuildArch:      noarch

%description    devel
Bindings to the libbacktrace gcc library.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.11-1
- Initial package
