# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate shell-escape

Name:           rust-%{crate}
Version:        0.1.3
Release:        1%{?dist}
Summary:        Escape characters that may have a special meaning in a shell

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/shell-escape
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Escape characters that may have a special meaning in a shell.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Mon Jul 03 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.3-1
- Initial package
