# Generated by rust2rpm
# No network for testing crates.io-index
%bcond_with check
%global debug_package %{nil}

%global crate semver

Name:           rust-%{crate}
Version:        0.6.0
Release:        2%{?dist}
Summary:        Semantic version parsing and comparison

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/semver
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(semver-parser) >= 0.7.0 with crate(semver-parser) < 0.8.0)
%if %{with check}
BuildRequires:  (crate(crates-index) >= 0.5.0 with crate(crates-index) < 0.6.0)
BuildRequires:  (crate(tempdir) >= 0.3.4 with crate(tempdir) < 0.4.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Semantic version parsing and comparison.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.0-2
- Port to use rust-packaging

* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.0-1
- Initial package
