# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate itertools

Name:           rust-%{crate}
Version:        0.5.9
Release:        1%{?dist}
Summary:        Extra iterator adaptors, iterator methods, free functions, and macros

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/itertools
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
BuildRequires:  (crate(either) >= 1.0.0 with crate(either) < 2.0.0)
%if %{with check}
BuildRequires:  (crate(permutohedron) >= 0.2.0 with crate(permutohedron) < 0.3.0)
BuildRequires:  (crate(quickcheck) >= 0.4.0 with crate(quickcheck) < 0.5.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Extra iterator adaptors, iterator methods, free functions, and macros.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.rst
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.9-1
- Initial package
