# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate termcolor

Name:           rust-%{crate}
Version:        0.3.1
Release:        1%{?dist}
Summary:        Simple cross platform library for writing colored text to a terminal

# https://github.com/BurntSushi/ripgrep/issues/381
License:        Unlicense or MIT
URL:            https://crates.io/crates/termcolor
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
Patch0:         termcolor-0.3.1-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
A simple cross platform library for writing colored text to a terminal.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%doc README.md 
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Wed Mar 15 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.1-1
- Update to 0.3.1

* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.0-1
- Update to 0.3.0

* Sat Feb 18 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-1
- Initial package
