# Generated by rust2rpm
# https://github.com/sfackler/rust-openssl/issues/612
%bcond_with check
%global debug_package %{nil}

%global crate openssl

Name:           rust-%{crate}
Version:        0.9.10
Release:        1%{?dist}
Summary:        OpenSSL bindings

License:        ASL 2.0
URL:            https://crates.io/crates/openssl
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * No windows
# * No paths
# * Bump bitflags, https://github.com/sfackler/rust-openssl/pull/611
Patch0:         openssl-0.9.10-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
# [dependencies]
BuildRequires:  (crate(bitflags) >= 0.8.0 with crate(bitflags) < 0.9.0)
BuildRequires:  (crate(foreign-types) >= 0.2.0 with crate(foreign-types) < 0.3.0)
BuildRequires:  (crate(lazy_static) >= 0.2.0 with crate(lazy_static) < 0.3.0)
BuildRequires:  (crate(libc) >= 0.2.0 with crate(libc) < 0.3.0)
BuildRequires:  (crate(openssl-sys) >= 0.9.10 with crate(openssl-sys) < 0.10.0)
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(hex) >= 0.2.0 with crate(hex) < 0.3.0)
BuildRequires:  (crate(tempdir) >= 0.3.0 with crate(tempdir) < 0.4.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
OpenSSL bindings.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Mon Apr 03 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.10-1
- Initial package
