# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate arrayref

Name:           rust-%{crate}
Version:        0.3.4
Release:        1%{?dist}
Summary:        Macros to take array references of slices

License:        BSD
URL:            https://crates.io/crates/arrayref
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(quickcheck) >= 0.4.0 with crate(quickcheck) < 0.5.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Macros to take array references of slices.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Tue Jun 20 2017 Martin Sehnoutka <msehnout@redhat.com> - 0.3.4-1
- Initial package
