# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate bincode

Name:           rust-%{crate}
Version:        0.8.0
Release:        1%{?dist}
Summary:        Binary serialization / deserialization strategy that uses Serde

License:        MIT
URL:            https://crates.io/crates/bincode
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * Replace 1.*.* with 1.* until we have support in rust2rpm
Patch0:         bincode-0.8.0-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(byteorder) >= 1.0.0 with crate(byteorder) < 2.0.0)
BuildRequires:  (crate(num-traits) >= 0.1.32 with crate(num-traits) < 0.2.0)
BuildRequires:  (crate(serde) >= 1.0.0 with crate(serde) < 2.0.0)
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(serde_bytes) >= 0.10.0 with crate(serde_bytes) < 0.11.0)
BuildRequires:  (crate(serde_derive) >= 1.0.0 with crate(serde_derive) < 2.0.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
A binary serialization / deserialization strategy that uses Serde for
transforming structs into bytes and vice versa!

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE.md
%doc readme.md readme.dev.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.0-1
- Initial package
