# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate coco

Name:           rust-%{crate}
Version:        0.1.1
Release:        1%{?dist}
Summary:        Concurrent collections

License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/coco
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(either) >= 1.0.0 with crate(either) < 2.0.0)
BuildRequires:  (crate(scopeguard) >= 0.3.0 with crate(scopeguard) < 0.4.0)
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(rand) >= 0.3.0 with crate(rand) < 0.4.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Concurrent collections.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Thu Jun 15 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-1
- Initial package
