# Generated by rust2rpm
%bcond_without check

%global crate rustfmt

Name:           %{crate}
Version:        0.7.1
Release:        2%{?dist}
Summary:        Tool to find and fix Rust formatting issues

# https://github.com/rust-lang-nursery/rustfmt/issues/1340
License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/rustfmt
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * No windows
Patch0:         rustfmt-0.7.1-fix-metadata.diff
# https://github.com/rust-lang-nursery/rustfmt/pull/1338
Patch1:         0001-bump-env_logger-to-0.4.patch
Patch2:         0002-bump-regex-to-0.2.patch
Patch3:         0003-bump-syntex_-to-0.58.patch

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
# [dependencies]
BuildRequires:  (crate(diff) >= 0.1.0 with crate(diff) < 0.2.0)
BuildRequires:  (crate(env_logger) >= 0.4.0 with crate(env_logger) < 0.5.0)
BuildRequires:  (crate(getopts) >= 0.2.0 with crate(getopts) < 0.3.0)
BuildRequires:  (crate(itertools) >= 0.5.8 with crate(itertools) < 0.6.0)
BuildRequires:  (crate(libc) >= 0.2.11 with crate(libc) < 0.3.0)
BuildRequires:  (crate(log) >= 0.3.0 with crate(log) < 0.4.0)
BuildRequires:  (crate(multimap) >= 0.3.0 with crate(multimap) < 0.4.0)
BuildRequires:  (crate(regex) >= 0.2.0 with crate(regex) < 0.3.0)
BuildRequires:  (crate(rustc-serialize) >= 0.3.0 with crate(rustc-serialize) < 0.4.0)
BuildRequires:  (crate(strings) >= 0.0.1 with crate(strings) < 0.0.2)
BuildRequires:  (crate(syntex_errors) >= 0.58.0 with crate(syntex_errors) < 0.59.0)
BuildRequires:  (crate(syntex_syntax) >= 0.58.0 with crate(syntex_syntax) < 0.59.0)
BuildRequires:  (crate(term) >= 0.4.0 with crate(term) < 0.5.0)
BuildRequires:  (crate(toml) >= 0.2.1 with crate(toml) < 0.3.0)
BuildRequires:  (crate(unicode-segmentation) >= 1.0.0 with crate(unicode-segmentation) < 2.0.0)
# [build-dependencies]
BuildRequires:  (crate(walkdir) >= 1.0.3 with crate(walkdir) < 2.0.0)

%description
%{summary}.

%package     -n rust-%{crate}-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{crate}-devel
Tool to find and fix Rust formatting issues.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%{_bindir}/rustfmt
%{_bindir}/cargo-fmt

%files       -n rust-%{crate}-devel
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.1-2
- Rebuild

* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.1-1
- Initial package
