# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate strsim

Name:           rust-%{crate}
Version:        0.6.0
Release:        2%{?dist}
Summary:        Implementations of string similarity metrics

License:        MIT
URL:            https://crates.io/crates/strsim
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
%{summary}.

%prep
%autosetup -n %{crate}-%{version}
%cargo_prep

%build
%cargo_build

%install
%cargo_install
# Some script which pulls /usr/bin/env shebang
rm -vf %{buildroot}%{cargo_registry}/%{crate}-%{version}/dev

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.0-2
- Port to use rust-packaging

* Sun Feb 12 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.0-1
- Initial package
