# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate serde_derive_internals

Name:           rust-%{crate}
Version:        0.15.1
Release:        1%{?dist}
Summary:        AST representation used by Serde derive macros

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/serde_derive_internals
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  ((crate(syn) >= 0.11.10 with crate(syn) < 0.12.0) with crate(syn/parsing))
BuildRequires:  (crate(synom) >= 0.11.0 with crate(synom) < 0.12.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
AST representation used by Serde derive macros. Unstable.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Thu Jun 15 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.15.1-1
- Initial package
