# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate maplit

Name:           rust-%{crate}
Version:        0.1.4
Release:        1%{?dist}
Summary:        Container / collection literal macros for HashMap, HashSet, BTreeMap, BTreeSet

# https://github.com/bluss/maplit/issues/11
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/maplit
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Container / collection literal macros for HashMap, HashSet, BTreeMap, BTreeSet.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE
%doc README.rst
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Thu Jul 06 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.4-1
- Initial package
