# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate linked-hash-map

Name:           rust-%{crate}
Version:        0.4.2
Release:        2%{?dist}
Summary:        HashMap wrapper that holds key-value pairs in insertion order

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/linked-hash-map
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * clippy is nightly
Patch0:         linked-hash-map-0.4.2-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(heapsize) >= 0.3.9 with crate(heapsize) < 0.4.0)
BuildRequires:  (crate(serde) >= 0.9.0 with crate(serde) < 0.10.0)
BuildRequires:  (crate(serde_test) >= 0.9.0 with crate(serde_test) < 0.10.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
A HashMap wrapper that holds key-value pairs in insertion order.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.2-2
- Port to use rust-packaging

* Thu Mar 30 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.2-1
- Update to 0.4.2

* Sat Feb 25 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.1-1
- Initial package
