# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate matches

Name:           rust-%{crate}
Version:        0.1.4
Release:        1%{?dist}
Summary:        Macro to evaluate, as a boolean, whether an expression matches a pattern

License:        MIT
URL:            https://crates.io/crates/matches
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
%{summary}.

%prep
%autosetup -n %{crate}-%{version}
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sun Feb 12 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.4-1
- Initial package
