# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate tokio-core

Name:           rust-%{crate}
Version:        0.1.8
Release:        1%{?dist}
Summary:        Core I/O and event loop primitives for asynchronous I/O in Rust

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/tokio-core
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * Bump env_logger to 0.4, https://github.com/tokio-rs/tokio-core/pull/219
Patch0:         tokio-core-0.1.8-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(bytes) >= 0.4.0 with crate(bytes) < 0.5.0)
BuildRequires:  (crate(futures) >= 0.1.14 with crate(futures) < 0.2.0)
BuildRequires:  (crate(iovec) >= 0.1.0 with crate(iovec) < 0.2.0)
BuildRequires:  (crate(log) >= 0.3.0 with crate(log) < 0.4.0)
BuildRequires:  (crate(mio) >= 0.6.9 with crate(mio) < 0.7.0)
BuildRequires:  (crate(scoped-tls) >= 0.1.0 with crate(scoped-tls) < 0.2.0)
BuildRequires:  (crate(slab) >= 0.3.0 with crate(slab) < 0.4.0)
BuildRequires:  (crate(tokio-io) >= 0.1.0 with crate(tokio-io) < 0.2.0)
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(env_logger) >= 0.4.0 with crate(env_logger) < 0.5.0)
BuildRequires:  (crate(libc) >= 0.2.0 with crate(libc) < 0.3.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Core I/O and event loop primitives for asynchronous I/O in Rust. Foundation for
the rest of the tokio crates.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.8-1
- Initial package
