# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate serde

Name:           rust-%{crate}0.8
Version:        0.8.23
Release:        2%{?dist}
Summary:        Generic serialization/deserialization framework

# https://github.com/serde-rs/serde/issues/772
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/serde
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * clippy is nightly
Patch0:         serde-0.8.23-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
A generic serialization/deserialization framework.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.23-2
- Port to use rust-packaging

* Sat Feb 25 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.23-1
- Initial package
