# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate unicode-width

Name:           rust-%{crate}
Version:        0.1.4
Release:        1%{?dist}
Summary:        Determine displayed width of `char` and `str` types according to Unicode Standard Annex #11 rules

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/unicode-width
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
%{summary}.

%prep
%autosetup -n %{crate}-%{version}
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sun Feb 12 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.4-1
- Initial package
