# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate openssl-probe

Name:           rust-%{crate}
Version:        0.1.1
Release:        1%{?dist}
Summary:        Tool for helping to find SSL certificate locations on the system for OpenSSL

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/openssl-probe
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Tool for helping to find SSL certificate locations on the system for OpenSSL.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Mon Jul 03 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-1
- Initial package
