# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate tempfile

Name:           rust-%{crate}
Version:        2.1.5
Release:        4%{?dist}
Summary:        Securely create temporary files

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/tempfile
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * No Windows
# * Remove rustc_version, https://github.com/Stebalien/tempfile/commit/0b7e0d573a2351d4f0a6e4ed833bc6ffdbc0dd4f
Patch0:         tempfile-2.1.5-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(libc) >= 0.2.0 with crate(libc) < 0.3.0)
BuildRequires:  (crate(rand) >= 0.3.0 with crate(rand) < 0.4.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Securely create temporary files.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
rm -vf build.rs
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md NEWS
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Thu Jun 15 2017 Igor Gnatenko <ignatenkobrain@fedoraproejct.org> - 2.1.5-4
- Drop rustc_version BR

* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.1.5-3
- Port to use rust-packaging

* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.1.5-2
- Rebuild

* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.1.5-1
- Initial package
