# Generated by rust2rpm
# Tests require networking, "google.com:443".to_socket_addrs()
%bcond_with check
%global debug_package %{nil}

%global crate tokio-openssl

Name:           rust-%{crate}
Version:        0.1.3
Release:        1%{?dist}
Summary:        Implementation of SSL streams for Tokio backed by OpenSSL

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/tokio-openssl
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(futures) >= 0.1.11 with crate(futures) < 0.2.0)
BuildRequires:  (crate(openssl) >= 0.9.14 with crate(openssl) < 0.10.0)
BuildRequires:  (crate(tokio-core) >= 0.1.6 with crate(tokio-core) < 0.2.0)
BuildRequires:  (crate(tokio-io) >= 0.1.0 with crate(tokio-io) < 0.2.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
An implementation of SSL streams for Tokio backed by OpenSSL.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.3-1
- Initial package
