# Generated by rust2rpm
%bcond_without check

%global crate rustfilt

Name:           rust-%{crate}
Version:        0.2.0
Release:        2%{?dist}
Summary:        Demangle Rust symbol names

License:        ASL 2.0
URL:            https://crates.io/crates/rustfilt
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  ((crate(clap) >= 2.21.1 with crate(clap) < 3.0.0) with crate(clap/wrap_help))
BuildRequires:  (crate(lazy_static) >= 0.2.4 with crate(lazy_static) < 0.3.0)
BuildRequires:  (crate(regex) >= 0.2.1 with crate(regex) < 0.3.0)
BuildRequires:  (crate(rustc-demangle) >= 0.1.4 with crate(rustc-demangle) < 0.2.0)

%description
%{summary}.

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate}
%{summary}.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files       -n %{crate}
%license LICENSE
%doc README.md
%{_bindir}/rustfilt

%changelog
* Wed Jul 05 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-2
- Rebuild for clap

* Thu Jun 15 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-1
- Update to 0.2.0

* Tue Jun 13 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-7
- Port to use rust-packaging

* Wed Mar 15 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-6
- Rename with rust prefix

* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-5
- Rebuild (rustc-demangle)

* Fri Feb 24 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-4
- Use rich dependencies

* Sun Feb 12 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-3
- Sync with rust2rpm generator

* Fri Feb 10 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-2
- Sync with rust2rpm generator
- Add doc/license

* Fri Feb 10 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-1
- Initial package
