# Generated by rust2rpm
%bcond_without check

%global crate rustfilt

Name:           %{crate}
Version:        0.1.1
Release:        5%{?dist}
Summary:        Demangle Rust symbol names

License:        ASL 2.0
URL:            https://crates.io/crates/rustfilt
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
BuildRequires:  (crate(rustc-demangle) >= 0.1.2 with crate(rustc-demangle) < 0.2.0)

%description
%{summary}.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/rustfilt

%changelog
* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-5
- Rebuild (rustc-demangle)

* Fri Feb 24 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-4
- Use rich dependencies

* Sun Feb 12 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-3
- Sync with rust2rpm generator

* Fri Feb 10 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-2
- Sync with rust2rpm generator
- Add doc/license

* Fri Feb 10 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.1-1
- Initial package
