# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate serde_derive

Name:           rust-%{crate}
Version:        0.9.7
Release:        1%{?dist}
Summary:        Macros 1.1 implementation of #[derive(Serialize, Deserialize)]

# https://github.com/serde-rs/serde/issues/772
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/serde_derive
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# [workspace] path
Patch0:         serde_derive-0.9.7-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
BuildRequires:  crate(quote) >= 0.3.8
BuildRequires:  crate(serde_codegen_internals) = 0.13.0
BuildRequires:  crate(syn/aster) >= 0.11.0
BuildRequires:  crate(syn/visit) >= 0.11.0
BuildConflicts: crate(quote) >= 0.4.0
BuildConflicts: crate(syn/aster) >= 0.12.0
BuildConflicts: crate(syn/visit) >= 0.12.0

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Macros 1.1 implementation of #[derive(Serialize, Deserialize)].

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sat Feb 18 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.7-1
- Initial package
