# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate quick-error

Name:           rust-%{crate}
Version:        1.2.0
Release:        1%{?dist}
Summary:        Macro which makes error types pleasant to write

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/quick-error
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
A macro which makes error types pleasant to write.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.rst
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Thu Jul 06 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.2.0-1
- Initial package
