# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate cmake

Name:           rust-%{crate}
Version:        0.1.21
Release:        2%{?dist}
Summary:        Build dependency for running `cmake` to build a native library

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/cmake
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(gcc) >= 0.3.17 with crate(gcc) < 0.4.0)
BuildRequires:  %{_bindir}/cmake

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       %{_bindir}/cmake

%description    devel
A build dependency for running `cmake` to build a native library.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.21-2
- Port to use rust-packaging

* Tue Feb 28 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.21-1
- Update to 0.1.21

* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.20-1
- Initial package
