# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate untrusted

Name:           rust-%{crate}
Version:        0.6.0
Release:        1%{?dist}
Summary:        Safe and fast parsing of untrusted inputs in Rust

License:        ISC
URL:            https://crates.io/crates/untrusted
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Safe, fast, zero-panic, zero-crashing, zero-allocation parsing of untrusted
inputs in Rust.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE.txt
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Sep 22 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.0-1
- Update to 0.6.0

* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.0-1
- Initial package
