# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate fnv

Name:           rust-%{crate}
Version:        1.0.5
Release:        1%{?dist}
Summary:        Fowler–Noll–Vo hash function

# https://github.com/servo/rust-fnv/issues/13
License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/fnv
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Fowler–Noll–Vo hash function.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sat Feb 25 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.5-1
- Initial package
