# Generated by rust2rpm
%bcond_with check
%global debug_package %{nil}

%global crate utf8-ranges

Name:           rust-%{crate}
Version:        1.0.0
Release:        1%{?dist}
Summary:        Convert ranges of Unicode codepoints to UTF-8 byte ranges

License:        Unlicense or MIT
URL:            https://crates.io/crates/utf8-ranges
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
%if %{with check}
BuildRequires:  crate(quickcheck) >= 0.4.1
BuildConflicts: crate(quickcheck) >= 0.5.0
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Convert ranges of Unicode codepoints to UTF-8 byte ranges.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license UNLICENSE LICENSE-MIT COPYING
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sat Feb 18 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.0-1
- Initial package
