# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate thread_local

Name:           rust-%{crate}
Version:        0.3.2
Release:        2%{?dist}
Summary:        Per-object thread-local storage

License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/thread_local
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
BuildRequires:  (crate(thread-id) >= 3.0.0 with crate(thread-id) < 4.0.0)
BuildRequires:  (crate(unreachable) >= 0.1.0 with crate(unreachable) < 0.2.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Per-object thread-local storage.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Feb 24 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.2-2
- Use rich dependencies

* Sat Feb 18 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.2-1
- Initial package
