# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate thread_local

Name:           rust-%{crate}
Version:        0.3.3
Release:        4%{?dist}
Summary:        Per-object thread-local storage

License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/thread_local
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * Bump unreachable to 1.0, https://github.com/Amanieu/thread_local-rs/pull/7
Patch0:         thread_local-0.3.3-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(thread-id) >= 3.0.0 with crate(thread-id) < 4.0.0)
BuildRequires:  (crate(unreachable) >= 1.0.0 with crate(unreachable) < 2.0.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Per-object thread-local storage.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.3-4
- Bump unreachable dependency to 1.0

* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.3-3
- Port to use rust-packaging

* Fri Feb 24 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.3-2
- Update to 0.3.3

* Fri Feb 24 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.2-2
- Use rich dependencies

* Sat Feb 18 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.2-1
- Initial package
