# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate net2

Name:           rust-%{crate}
Version:        0.2.29
Release:        1%{?dist}
Summary:        Extensions to the standard library's networking types as proposed in RFC 1158

License:        MIT or ASL 2.0
URL:            https://crates.io/crates/net2
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * No windows
Patch0:         net2-0.2.29-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(cfg-if) >= 0.1.0 with crate(cfg-if) < 0.2.0)
BuildRequires:  (crate(libc) >= 0.2.14 with crate(libc) < 0.3.0)
BuildRequires:  (crate(libc) >= 0.2.14 with crate(libc) < 0.3.0)
BuildRequires:  (crate(libc) >= 0.2.14 with crate(libc) < 0.3.0)
BuildRequires:  (crate(libc) >= 0.2.14 with crate(libc) < 0.3.0)
BuildRequires:  (crate(libc) >= 0.2.14 with crate(libc) < 0.3.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Extensions to the standard library's networking types as proposed in RFC 1158.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.29-1
- Initial package
