# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate crossbeam

Name:           rust-%{crate}
Version:        0.2.10
Release:        1%{?dist}
Summary:        Support for lock-free data structures, synchronizers, and parallel programming

License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/crossbeam
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust
BuildRequires:  cargo
%if %{with check}
BuildRequires:  (crate(rand) >= 0.3.0 with crate(rand) < 0.4.0)
%endif

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
Support for lock-free data structures, synchronizers, and parallel programming.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
# https://github.com/aturon/crossbeam/issues/111
rm -vrf src/bin/
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sun Feb 26 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.10-1
- Initial package
