# Generated by rust2rpm
%bcond_without check

%global crate base100

Name:           rust-%{crate}
Version:        0.2.0
Release:        1%{?dist}
Summary:        Encode your data into emoji

# https://github.com/AdamNiederer/base100/issues/2
License:        AGPLv3+
URL:            https://crates.io/crates/base100
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  ((crate(clap) >= 2.19.0 with crate(clap) < 3.0.0) with crate(clap/yaml))

%description
%{summary}.

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate}
%{summary}.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files       -n %{crate}
%doc README.md
%{_bindir}/base100

%changelog
* Fri Oct 06 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-1
- Initial package
